
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.camposeco.proyecto1_compiladores.analizador.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIGITOS = 62;
  public static final int DIAGONAL = 11;
  public static final int RESTO = 7;
  public static final int ENTERO = 57;
  public static final int CASE = 49;
  public static final int DOUBLE = 61;
  public static final int COMILLA_LETRA = 56;
  public static final int PRIVATE = 37;
  public static final int DOS_PUNTOS = 5;
  public static final int CORCHETE_C = 17;
  public static final int CORCHETE_A = 16;
  public static final int LLAVE_C = 13;
  public static final int ASTERISCO = 10;
  public static final int COMENTARIO_LINEA = 43;
  public static final int FOR = 33;
  public static final int LLAVE_A = 12;
  public static final int NOT = 28;
  public static final int AND = 26;
  public static final int IGUAL = 2;
  public static final int CARACTER = 60;
  public static final int OR = 27;
  public static final int INCREMENTO = 24;
  public static final int IMPORTAR = 29;
  public static final int IF = 31;
  public static final int THIS = 51;
  public static final int PUNTO_COMA = 6;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int PALABRA = 54;
  public static final int CLASE = 47;
  public static final int TRUE = 46;
  public static final int NEW = 52;
  public static final int DECREMENTO = 25;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int CADENA = 59;
  public static final int MENOS = 9;
  public static final int MAYOR_QUE = 19;
  public static final int BREAK = 41;
  public static final int VOID = 48;
  public static final int SWITCH = 36;
  public static final int COMENTARIO_MULTILINEA = 44;
  public static final int ELSE = 32;
  public static final int PROTECTED = 39;
  public static final int PUNTO = 4;
  public static final int PARENTESIS_C = 15;
  public static final int FINAL = 40;
  public static final int IGUAL_A = 20;
  public static final int WHILE = 34;
  public static final int PARENTESIS_A = 14;
  public static final int DEFAULT = 50;
  public static final int MAYOR_IGUAL = 23;
  public static final int PUBLIC = 38;
  public static final int BOOLEANO = 58;
  public static final int OBJETO = 30;
  public static final int MENOR_QUE = 18;
  public static final int TEXTO = 53;
  public static final int MENOR_IGUAL = 22;
  public static final int DISTINTO_A = 21;
  public static final int FALSE = 45;
  public static final int DO = 35;
  public static final int COMILLAS_TEXTO = 55;
  public static final int MAS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "COMA",
  "PUNTO",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "RESTO",
  "MAS",
  "MENOS",
  "ASTERISCO",
  "DIAGONAL",
  "LLAVE_A",
  "LLAVE_C",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "MENOR_QUE",
  "MAYOR_QUE",
  "IGUAL_A",
  "DISTINTO_A",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "INCREMENTO",
  "DECREMENTO",
  "AND",
  "OR",
  "NOT",
  "IMPORTAR",
  "OBJETO",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "SWITCH",
  "PRIVATE",
  "PUBLIC",
  "PROTECTED",
  "FINAL",
  "BREAK",
  "RETURN",
  "COMENTARIO_LINEA",
  "COMENTARIO_MULTILINEA",
  "FALSE",
  "TRUE",
  "CLASE",
  "VOID",
  "CASE",
  "DEFAULT",
  "THIS",
  "NEW",
  "TEXTO",
  "PALABRA",
  "COMILLAS_TEXTO",
  "COMILLA_LETRA",
  "ENTERO",
  "BOOLEANO",
  "CADENA",
  "CARACTER",
  "DOUBLE",
  "DIGITOS"
  };
}

